haipumpfinder/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from array import array
from django.conf.urls import url
from django.contrib import admin 
from django.contrib.auth import views as auth_views
from accounts import views as accounts_views
from trialfinder import views as trialfinder_views
from haipumpfinder import views as HPViews
app_name = 'haipumpfinder'

urlpatterns = [
    path(r'what-the-hai', TemplateView.as_view(template_name="haipumpfinder/what-the-hai.html")),
    path(r'hai-in-the-news', TemplateView.as_view(template_name="haipumpfinder/news.html")),
    path('', HPViews.IndexView.as_view(), name='index'),
    path('<int:pk>/', HPViews.DetailView.as_view(), name='detail'),
    path(r'trial/<str:trial_id>', HPViews.trial, name='trial'),
    path(r'signup/', accounts_views.signup, name='signup'),  
    path(r'success/', accounts_views.success, name='success'),
    path(r'profile/', accounts_views.profile_view, name='profile'), 
    
    path(r'detail-treatment/', accounts_views.detail_treatment, name='detail_treatment'),   
    path(r'add-treatment/', accounts_views.add_treatment, name='add_treatment'), 
    path(r'password_change/', auth_views.password_change, name='password_change'),   
    path(r'logout/', auth_views.logout, name='logout'),    
    path(r'login/', auth_views.login, name='login'), 
    path(r'trial/<str:trial_id>', HPViews.trial, name='treatment'),
    #path('accounts/', include('django.contrib.auth.urls')),
 ]

haipumpwww/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('haipumpfinder/', include('haipumpfinder.urls')),
    path('admin/', admin.site.urls),
    path('trialfinder/', include('trialfinder.urls', namespace="trialfinder")),
    
]

haipumpfinder/models.py
from django.db import models 
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

STAGE0 = '0'
STAGE1 = '1'
STAGE2 = '2'
STAGE3 = '3'
STAGE3a = '3a'
STAGE3b = '3b'
STAGE3c = '3c'
STAGE4 = '4'
STAGES = (
    (STAGE1, 'I'),
    (STAGE2, 'II'),
    (STAGE3, 'III'),
    (STAGE3, 'III A'),
    (STAGE3, 'III B'),
    (STAGE3, 'III C'),
    (STAGE4, 'IV'),
    )
MSISTATUS = (
    ("MSS", 'MSS'),
    ("MSIH", 'MSI-H'),
    )
NED = (
    ("YES", 'Yep'),
    ("NO", 'Nope'),
    )

class BiomarkersLookUp(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)  
 

class Patient(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, editable=False)
    dx_date = models.DateField(blank=True, null=True)
    last_treatment_date = models.DateField(blank=True, null=True)
    ned = models.CharField(
        max_length=20,
        choices=NED,
        default="YES",
    )
    stage_now = models.CharField(
        max_length=20,
        choices=STAGES,
        default=STAGE1,
    )
    stage_at_dx = models.CharField(
        max_length=20,
        choices=STAGES,
        default=STAGE1,
    )
    msi_status = models.CharField(
        max_length=20,
        choices=MSISTATUS,
        default="MSS",
    )

    biomarkers = models.ManyToManyField(BiomarkersLookUp)
    
   
    class Meta:
        managed = True
        db_table = 'patient'

@receiver(post_save, sender=User)
def create_or_update_user_patient(sender, instance, created, **kwargs):
    if created:
        Patient.objects.create(user=instance)
    instance.patient.save()

@receiver(post_save, sender=User)
def save_user_patient(sender, instance, **kwargs):
    instance.patient.save()

DEFAULT_PATIENT_ID = 1
class Treatment(models.Model):
    description = models.TextField(max_length=255)
    trial_id = models.CharField(max_length=100)
    dose_schedule = models.TextField(max_length=255)
    start_date = models.DateField(blank=True, null=True)
    last_treatment_date = models.DateField(blank=True, null=True)
    response = models.TextField(max_length=255)
    treatment_notes = models.TextField(max_length=255)
    side_effect = models.TextField(max_length=255)
    patient = models.ForeignKey(Patient, default = DEFAULT_PATIENT_ID,  on_delete=models.CASCADE,)

    def __str__(self):
        return self.desciption

    class Meta:
        ordering = ('start_date',) 
        db_table = 'treatment'

class Hospital(models.Model):
    name = models.CharField(db_column='Name', max_length=255, blank=True, null=True)  # Field name made lowercase.
    address = models.CharField(db_column='Address', max_length=255, blank=True, null=True)  # Field name made lowercase.
    city = models.CharField(db_column='City', max_length=255, blank=True, null=True)  # Field name made lowercase.
    state = models.CharField(db_column='State', max_length=50, blank=True, null=True)  # Field name made lowercase.
    zip = models.CharField(db_column='Zip', max_length=20, blank=True, null=True)  # Field name made lowercase.
    phone = models.CharField(db_column='Phone', max_length=20, blank=True, null=True)  # Field name made lowercase.
    field_colontown_patients = models.CharField(db_column='# ColonTown Patients', max_length=100, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters. Field renamed because it started with '_'.
    guestimated_of_hai_implants_per_year = models.CharField(db_column='Guestimated # of HAI Implants per year', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    url = models.CharField(db_column='URL', max_length=255, blank=True, null=True)  # Field name made lowercase.
    ct_contacts = models.CharField(db_column='CT Contacts', max_length=255, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    longitude = models.CharField(db_column='Longitude', max_length=20, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    latitude = models.CharField(db_column='Latitude', max_length=20, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
   
    def __str__(self):
        return self.name
    class Meta:
        managed = True
        db_table = 'hospital'

haipumpfinder/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
 

 
  

haipumpfinder/views.py
from django.shortcuts import get_object_or_404, render, HttpResponse, Http404
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.template import Context, Template 
from django.urls import reverse
from django.views import generic
#import pdb; pdb.set_trace()
from .services import Trial, TrialLocation
from .models import Hospital 



def trial(request,trial_id):
    t = Trial(trial_id) 
    print("Trial Name: " + t.name)
    page_title = "Trial Finder- Finds clinics offering the " + t.name
    #print("Trial URL :" + t.CTGovURL)
    try:
        sites_list = t.locations 
    except:
        raise Http404("Trial ID not found") 

    sites_dict = {
        'sites_list': sites_list,
        'trial_name': t.name,
        'trial_id': trial_id,
        'page_title': page_title,
    }
    return render(request,'haipumpfinder/trial.html', sites_dict)

# console.log('Got here bitch!')
#sites_list = Trial.locations('NCT02928224')
#print("Sites Count: " + sites_list[0].city)
#return HttpResponse("Got test to Trial!")
#return render(request,'trial.html',sites_list) 





class IndexView(generic.ListView):
    page_title = "HAI Pump Finder- Finds clinics offering the HAI Pump"
    template_name = 'haipumpfinder/index.html'
    context_object_name = 'hospital_list'
    #print(Hospital.objects.count())
    def get_queryset(self):
        """Return all published hospitals."""
        return Hospital.objects.order_by('id')


class DetailView(generic.DetailView):
    model = Hospital
    template_name = 'haipumpfinder/detail.html'



class ResultsView(generic.DetailView):
    template_name = 'haipumpfinder/what-the-hai.html'

class ResultsView(generic.DetailView):
    template_name = 'haipumpfinder/news.html'

#class Address_List(Hospitals)
#     @property
#    def get_address(self):
#        address_list = []  
#        for hospital in Hospital.objects.all()
#          address_list = address_list.append[hospital.city]  
#        endfor 
#        return address_list

haipumpfinder/templates/haipumpfinder/base.html
<!DOCTYPE html>
{% load static %} 


<html>
    
<meta charset="utf-8">
<head>   
  
<title>
        {% block title %}
          {% if page_title %}
            {{ page_title }}
          {% else %}
            HAI Pump Finder - Find some HAI Pumps near you.
          {% endif %}
          
        {% endblock %}
</title>
<meta name="description" content="Find a Cancer Clinic or Hospital offering the HAI PUMP near you. Get directions, meet others trying the HAI Pump by joining Colontown." />
<meta property="og:title" content="Locations | HAI Pump Clinics" />
<meta property="og:description" content="Find a Cancer Clinic or Hospital offering the HAI PUMP near you. Get directions, meet others trying the HAI Pump by joining Colontown." />
 
<script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="{% static '/haipumpfinder/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static '/haipumpfinder/sticky-footer.css' %}" />
<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{{ form.media }}

<link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}" />

</head>
<body>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/haipumpfinder">Magnesium & Hope</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'haipumpfinder:index' %}">HAI Pump Clinics<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                    <a class="nav-link" href="/haipumpfinder/what-the-hai">What's a HAI Pump?</a>
                  </li>
             <li class="nav-item">
                <a class="nav-link" target="_new" href="https://clinicaltrials.gov/ct2/show/NCT03366155">Join the NIH Clinical Trial</a>
              </li>
                        <li class="nav-item">
                <a class="nav-link" target="_new" href=" https://www.clinicaltrials.gov/ct2/show/NCT00645710">Join the COT Clinical Trial</a>
              </li>
             
              
          </ul>
          {% if user.is_authenticated %}
          <div class="collapse navbar-collapse" id="mainMenu">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                  <a class="dropdown-item" href="{% url 'haipumpfinder:profile' %}">My Profile</a>
                 <!-- <a class="dropdown-item" href="/haipumpfinder/password_change">Change password</a> -->
                  <a class="dropdown-item" href="{% url 'haipumpfinder:add_treatment' %}">Add a Treatment</a>  
                 <a class="dropdown-item" href="{% url 'trialfinder:index' %}">My Trials</a>
                 
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'haipumpfinder:logout' %}">Log out</a>
                </div>
              </li>
            </ul>
          </div>

            {% else %}
          <div class="form-inline my-2 my-lg-0">
              <button  onclick="goto_signup()" class="btn btn-outline-primary my-2 my-sm-0" type="submit">Sign Up</button>
              &nbsp;
              <button   onclick="goto_login()" class="btn btn-outline-success my-2 my-sm-0" type="submit">Login</button>
          </div>
          {% endif %}
         
        
        </div>
      </nav>
      <script>
          function goto_signup()
          {
               location.href = "{% url 'haipumpfinder:signup' %}";
          } 
          function goto_login()
          {
               location.href = "{% url 'haipumpfinder:login' %}";
          } 
          </script>
      {% endblock navbar %}

    
    {% block content %}{% endblock content %}


<footer class="footer">
<div class="container">
<span class="text-muted">Complaints? Better ideas? Don't hesitate! <a href="mailto:mike@radiantdays.com">mike@radiantdays.com</a></span>
</div>
</footer> 
</body>
</html>

haipumpfinder/templates/haipumpfinder/detailtreatment.html
<!DOCTYPE html>
{% extends 'haipumpfinder/base.html' %}
{% load static %}

{% block content %}
<div class="container">
            <div class="btn-group" role="group" aria-label="...">
                        <button type="button" class="btn btn-primary" onclick="goBack()">< Back</button>
                  
            </div>
            <script>
                        function goBack() {
                            window.history.back();
                        }
                        </script>
            <p></p>
            <h1>{{ hospital.name }}</h1>
            <p>Short intro</p>      
            <div class="row">
                  <div class="col-sm-2">
                  Address: 
                  </div>
                  <div class="col-sm-2">
                        {{ hospital.address }} 
                  </div>
            </div>
            <div class="row">
                  <div class="col-sm-2">
                   City: 
                  </div>
                  <div class="col-sm-2">
                      {{ hospital.city }}, {{ hospital.state }} {{ hospital.zip }}    
                  </div>
            </div>
            <div class="row">
                        <div class="col-sm-2">
                         # of CT Patients
                        </div>
                        <div class="col-sm-2">
                              <span class="badge badge-primary badge-pill"> 
                               {{ hospital.field_colontown_patients }}  
                              </span>     
                        </div>
            </div>
                  
            <div class="row">
                  <div class="col-sm-2">
                   Estimated implants per year
                  </div>
                  <div class="col-sm-2">
                  <span class="badge badge-primary badge-pill"> 
                        {{ hospital.guestimated_of_hai_implants_per_year }}  
                  </span>
                  </div>
            </div>
            <div class="row">
                        <div class="col-sm-2">
                         Website:
                        </div>
                        <div class="col-sm-2">
                              <!-- TODO Grab logos
                                    <img src=" https://apresgroup.com/wp-content/uploads/2017/02/iu-e1491373574945.png" 
                               class="img-thumbnail" alt="{{ hospital.name }}">
                              -->
                             
                              <a href="{{ hospital.url }}" target="_blank" title="{{ hospital.name }}">{{ hospital.url }}</a>
                        </div>
            </div>
            <div class="row">
            <div class="col-sm-4">

<!-- <h3>Location: {{ hospital.address }} {{ hospital.city }}, {{ hospital.state }}</h3> -->

<div id="trialmap-canvas"></div>
                  </div>
      </div>
      </div>
<script>

      var geocoder;
      var map;
   function initMap() {
      geocoder = new google.maps.Geocoder();
      var latlng = new google.maps.LatLng(37.09024, -95.712891);
      var mapOptions = {
        zoom: 8,
        center: latlng,
        mapTypeId: google.maps.MapTypeId.ROADMAP
      }
      map = new google.maps.Map(document.getElementById("trialmap-canvas"), mapOptions);
    }
    function codeAddress() {
      var address = '{{ hospital.address }} {{ hospital.city }}, {{ hospital.state }}';
      geocoder.geocode( { address: address}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          map.setCenter(results[0].geometry.location);
          var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
        });
        } else {
        alert("Geocode was not successful for the following reason: " + status);
        }
      });
    }
    
    window.onload = function() {
        initMap();
        codeAddress();
    }

  
</script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAxfDqt23sS87Q8ITlvZot6ADUhbSNkLEM&callback=initMap">
    </script>
      {% endblock %}

haipumpfinder/templates/haipumpfinder/index.html
<!DOCTYPE html>
{% extends 'haipumpfinder/base.html' %}
{% load static %}

{% block content %}
 
<div class="container">
        <p></p>
<h1>Let's find some HAI Pumps!</h1>  
<p>&nbsp;</p>     
<div id="map-canvas"></div>
</div>
<div class="container">
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
{% if hospital_list %}
<table id="HaiPumpTable" class="table table-hover" style="width:100%">
        <thead>
          <tr>
            <th scope="col">Cancer Clinic</th>
            <th scope="col">Location</th>
            <th scope="col">Phone</th>
            <th scope="col">Lat.</th>
            <th scope="col">Long.</th>
            <th scope="col"># of HAI Pumps/Year</th>
            <th scope="col"># CT members</th>
            
          </tr>
        </thead>
        <tbody>

          
    {%  for hospital in hospital_list %}
        <tr>
        <td><a href="{% url 'haipumpfinder:detail' hospital.id %}">{{ hospital.name }}</a></td>
        <td class="CityState">{{ hospital.city }}, {{ hospital.state }} </td>      
        <td class="Phone"><a href="tel:{{ hospital.phone }}">{{ hospital.phone }}</a></td>      
        <td class="Lat">{{ hospital.latitude }}</td>
        <td class="Long">{{ hospital.longitude }} </td>
       <td><span class="badge badge-primary badge-pill"> {{ hospital.guestimated_of_hai_implants_per_year }}</span></td>
        <td><span class="badge badge-primary badge-pill"> {{ hospital.field_colontown_patients }}</span></td>
    </tr>
    {% endfor %}
  
</tbody>
</table>

{% else %}
    <p>No hospitals are available.</p>
{% endif %}
</div>
  
 
 

<script>

  //make the datatable
        $(document).ready(function() {
            $('#HaiPumpTable').DataTable({
                "pageLength": 25,
                "lengthChange": false,
                "columnDefs": [
                {
                   "targets": [ 3 ],
                    "visible": false,
                    "searchable": false
                },
                {
                "targets": [ 4 ],
                 "visible": false
                 }
                        ]
            });
        } );

        var geocoder;
        var map;
        function initMap() {
            geocoder = new google.maps.Geocoder();
            var latlng = new google.maps.LatLng(37.09024, -95.712891);
            var mapOptions = {
              zoom: 4,
              center: latlng,
              mapTypeId: google.maps.MapTypeId.ROADMAP
            }
            map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
          }
         

function fillMap(callback) {
   
    var clinics = [];
        
    var map = new google.maps.Map(document.getElementById('map-canvas'), {
        zoom: 4,
        center: new google.maps.LatLng(37.09024, -95.712891),
        mapTypeId: google.maps.MapTypeId.ROADMAP
      });

      
      var HaiPumpTable = $('#HaiPumpTable').DataTable();
       HaiPumpTable.rows().every(function(){
           clinics.push({'name' : this.data()[0], 
             'city_state' : this.data()[1],
             'phone' : this.data()[2],
             'lat' : this.data()[3], 
             'long' : this.data()[4],
             'number_of_pumps' : this.data()[5],
             'ct_patients' : this.data()[6],
            });
            
       })

        var infowindow = new google.maps.InfoWindow();
        var marker, i;
        for (i = 0; i < clinics.length; i++) 
        {
            marker = new google.maps.Marker(
            {
                position: new google.maps.LatLng(clinics[i].lat, clinics[i].long),
                map: map
            });
    
            google.maps.event.addListener(marker, 'click', (function (marker, i) {
                return function () {
                    infowindow.setContent(clinics[i].name + "<br>" + clinics[i].city_state + 
                    "<br>Phone: " +  clinics[i].phone + 
                    "<br># of Pumps Implanted: " +  clinics[i].number_of_pumps + 
                    "<br>Colontown Patients: " +  clinics[i].ct_patients );
                    infowindow.open(map, marker);
                }
            })(marker, i));
        }
    }
 
 
 
      window.onload = function() {
          initMap();
          //codeAddress();
          fillMap(function() {
            // Do something after getting done with Geocoding of multiple addresses
              }); 
                 
              } 

  
    
  </script>
      <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAxfDqt23sS87Q8ITlvZot6ADUhbSNkLEM&callback=initMap">
      </script> 
 
<div class="container">
    <p>&nbsp;</p>
    <p>&nbsp;</p>
        <p>If you have questions or are interested in meeting others who have tried the HAI Pump, there's a HAI Pump support group in <a href="https://colontown.org/colontown-intake-form/" title="Colontown" target="_new">ColonTown</a>. 
        </p>
        <p> 
    We discuss side-effects, doctors, hospitals, and more. If you're a patient or caregiver, we highly recommend joining. 
        </p>
    </div> 
    
    <div class="container">
            <p> (<a href="https://colontown.org/colontown-intake-form/" title="Colontown" target="_new">ColonTown</a> does not endorse this site or HAI Pump treatment. I'm just a huge fan. It's a phenomenal community  of more than 80 “secret” groups on Facebook for colorectal patients, survivors, and caregivers. I'm a member and have found it to be an amazing community and place for information.)  
           </p>
    
     
    </div>
    
    

           
   
{% endblock %}

haipumpfinder/templates/haipumpfinder/logout.html
<!DOCTYPE html>
{% extends 'haipumpfinder/base.html' %}
{% load static %}

{% block content %}
 
<div class="container">
    <p></p>
  <h2>Got here. Should be logged out</h2>
  
  
</div> 
{% endblock %}

haipumpfinder/templates/haipumpfinder/signup.html
<!DOCTYPE html>
{% extends 'haipumpfinder/base.html' %}
{% load static %}
{% block content %}
<div class="container">
        <h1>Join Magnesium & Hope</h1>
        <p class="lead">A new way to find help.</p>
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message }}
        </div>
      {% endfor %}
        <!-- Show steps if user is creating an organiation -->
        <div class="row">
                <div class="col-sm"><svg height="32" class="octicon octicon-person" viewbox="0 0 12 16" version="1.1" width="24" aria-hidden="true"><path fill-rule="evenodd" d="M12 14.002a.998.998 0 0 1-.998.998H1.001A1 1 0 0 1 0 13.999V13c0-2.633 4-4 4-4s.229-.409 0-1c-.841-.62-.944-1.59-1-4 .173-2.413 1.867-3 3-3s2.827.586 3 3c-.056 2.41-.159 3.38-1 4-.229.59 0 1 0 1s4 1.367 4 4v1.002z"/></svg>
                    <strong class="step">Step 1:</strong>
                    Create personal account</div>
              
                <div class="col-sm">   <svg height="32" class="octicon octicon-heart" viewbox="0 0 14 16" version="1.1" width="28" aria-hidden="true"><path fill-rule="evenodd" d="M14 8.77v-1.6l-1.94-.64-.45-1.09.88-1.84-1.13-1.13-1.81.91-1.09-.45-.69-1.92h-1.6l-.63 1.94-1.11.45-1.84-.88-1.13 1.13.91 1.81-.45 1.09L0 7.23v1.59l1.94.64.45 1.09-.88 1.84 1.13 1.13 1.81-.91 1.09.45.69 1.92h1.59l.63-1.94 1.11-.45 1.84.88 1.13-1.13-.92-1.81.47-1.09L14 8.75v.02zM7 11c-1.66 0-3-1.34-3-3s1.34-3 3-3 3 1.34 3 3-1.34 3-3 3z"/></svg>
                    <strong class="step">Step 2:</strong>
                    Create your disease & treament profile</div>
               </div>
           
    </div>

 
<div class="container">
    <p></p>
  <h2>Create your personal account</h2>
  <p></p>

  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p> 
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <div class="btn-group" role="group">
        <button type="submit" class="btn btn-success">Create an Account</button>
  
</div>
  </form>
  </div>
  <div class="container">
        <p></p>
        <p></p><p></p><p></p>
        <!-- Show steps if user is creating an organiation -->
        <div class="row">
                <div class="col-sm" style=" border: 1px solid; width:200px;" >
                    Already have an account? <a href="{% url 'haipumpfinder:login' %}">login</a>
                </div>
           
    </div>
</div>
{% endblock %}

haipumpfinder/templates/haipumpfinder/treatmentslist.html
<div class="container">
        <p></p>
        <p></p><p></p><p></p> 
        <div class="row">
          <div class="col-sm" style=" border: 1px solid; width:200px;" >
              Treatments:
          </div>
      
      </div>
      <div class="row">
      {% if treatment_list %}
      
        <table id="TreatmentTable" class="table table-hover" style="width:100%">
              <thead>
                <tr>
                  <th scope="col">ID</th>
                  <th scope="col">Treatment Description</th>
                  <th scope="col">SOME Identifier</th> 
                  
                </tr>
              </thead>
              <tbody>
      
                
          {%  for treatment in treatment_list %}
              <tr>
              <td><a href="{% url 'haipumpfinder:detail' treatment.id %}">{{ treatment.id }}</a></td>
        
              <td> {{ treatment.start_date }} </td>
              <td class="Description">{{ treatment.description }} </td>
              
          </tr>
          {% endfor %}
        
      </tbody>
      </table>
      {% else %}
      No Treatments found
      {% endif %}
      
      </div>
      
      
        <div class="row">
                <div class="col-sm" style=" border: 1px solid; width:200px;" >
                      <a href="{% url 'haipumpfinder:add_treatment' %}" class="btn btn-default">Add a Treatment</a>
      
                  </div>
           
      </div>
      </div> 